admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

gestion_projet:
    resource: "@GestionProjetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
article:
    resource: "@GestionProjetBundle/Resources/config/routing/article.yml"
    prefix:   /article    
    
auteur:
    resource: "@GestionProjetBundle/Resources/config/routing/auteur.yml"
    prefix:   /auteur      

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 
      
# app/config/routing.yml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin 
    
# app/config/routing.yml

# ...
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin    