gestion_projet_article:
    resource: "@GestionProjetBundle/Resources/config/routing/article.yml"
    prefix:   /article

gestion_projet_homepage:
    path:     /
    defaults: { _controller: GestionProjetBundle:Default:index }
    
myapplication_contact:
    path:     /contact
    defaults: { _controller: GestionProjetBundle:Default:contact }    
     
    
layout:
    path:     /layout
    defaults: { _controller: GestionProjetBundle:Default:layout }    


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 